TINDER_URL = "https://api.gotinder.com"
DATE_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
PROF_DATA = "./data/profiles.csv"
IMAGE_FOLDER = "./data/unclassified"
POS_FOLDER = "./data/classified/positive"
NEG_FOLDER = "./data/classified/negative"
TOKEN = "YOUR-TOKEN-API"
